name: Java CI

# Trigger the workflow on push or pull request events on specific branches
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (or specify your required version)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Also consider 'zulu' or 'adopt' depending on your JDK preference
          java-version: '17'

      # Step 3: Cache the Maven repository to speed up the build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the Java project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 6: Fail the PR if the build or tests fail
      - name: Check for failure
        if: failure()
        run: echo "Build failed, please fix the errors before merging."
